### ISSUE TITLE
Running on Node

### ISSUE THREAD

**Issue by adrianAzoitei** [TheOtterlord/starlight-auth#4]
Hi!

Could you provide some guidance on how to run this project on Node? Works like a charm on Vercel, but couldn't figure out how to get from the src/server/index.ts to a server I can run on Node yet. Any hints would be greatly appreciated!

**Comment by adrianAzoitei** [comment]
Completely missed using `tsm` 😄 , works alright, though I had to install https://www.npmjs.com/package/server-destroy?activeTab=readme

**Comment by pdo-neuroclues** [comment]
> Completely missed using `tsm` 😄 , works alright, though I had to install https://www.npmjs.com/package/server-destroy?activeTab=readme

Hello, can you be more explicit on how you resolved this issue?
I have a working configuration that allow me to authenticate, but I can access the protected page without authentication.

I do not deploy on vercel, and only try locally.
Any idea?

**Comment by pdomineaux** [comment]
> Completely missed using `tsm` 😄 , works alright, though I had to install https://www.npmjs.com/package/server-destroy?activeTab=readme

Hello, can you be more explicit on how you resolved this issue?
I have a working configuration that allow me to authenticate, but I can access the protected page without authentication.

I do not deploy on vercel, and only try locally.
Any idea?

**Comment by adrianAzoitei** [comment]
> > Completely missed using `tsm` 😄 , works alright, though I had to install https://www.npmjs.com/package/server-destroy?activeTab=readme
> 
> Hello, can you be more explicit on how you resolved this issue? I have a working configuration that allow me to authenticate, but I can access the protected page without authentication.
> 
> I do not deploy on vercel, and only try locally. Any idea?

I added:
```js
output: "server",
adapter: node({
    mode: "middleware",
})
```
to `astro.config.mjs` and I am running the server with:
`tsm src/server/index.ts` (or `npx tsm ...` if you didn't install `tsm` globally like I did) after building the Astro project with `npm run build`.
